import {
  Geist,
  Geist_Mono,
  Space_Grotesk,
  Poppins,
  Istok_Web,
} from "next/font/google";
import "./globals.css";
import Navbar from "./component/layout/Navbar";
import Footer from "./component/layout/Footer";
import Loader from "./component/layout/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const istokWeb = Istok_Web({
  variable: "--font-istok-web",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Fire AI Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${poppins.variable} ${istokWeb.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col bg-[#fafafa] text-[#09090b]">
        <Loader>
          <Navbar />
          {children}
          <Footer />
        </Loader>
      </body>
    </html>
  );
}
